### ISSUE TITLE
[BUG反馈] 读取下一页错误，IndexError

### ISSUE THREAD

**Issue by Sun-ZhenXing** [xz454867105/fxxk_chaoxing#22]
**形容Bug的信息**
读取下一页错误，`IndexError`

**Screenshots**
```
482028125章0页读取完毕，查看下一页
482028125章1页读取完毕，查看下一页
482028125章读取完毕，开始读取下一章
482028126章0页读取完毕，查看下一页
482028126章1页读取完毕，查看下一页
482028126章读取完毕，开始读取下一章
开始读取后续章节
482028127章0页读取完毕，查看下一页
Traceback (most recent call last):
  File "D:\WorkSpace\for_shen\fxxk_chaoxing\main.py", line 16, in <module>
    doWork.do_ppt(session, mp4, ppt, usernm, course)
  File "D:\WorkSpace\for_shen\fxxk_chaoxing\src\course\doWork.py", line 211, in do_ppt
    load_ppt(session, course, ppt_done, chapter_done, chapters, usernm, ppt)
  File "D:\WorkSpace\for_shen\fxxk_chaoxing\src\course\doWork.py", line 258, in load_ppt
    result = re.findall('mArg = (.*?);', resq)[1]
IndexError: list index out of range
```

**运行环境 (请完善以下信息):**
 - 系统：Windows 21H1
 - Python环境版本:Python 3.9
 - 运行方式: 源代码运行

**其他内容**
- 课程名称 **大学生职业生涯规划（入学版）**
- 正则表达式匹配可能需要考虑？

**Comment by xz454867105** [comment]
你可以尝试在代码里把resq的url打印出来，然后在已经登陆的浏览器中打开，检查课程章节的显示是否正常
